### ISSUE TITLE
[DKG] SPARQL query that with time range beyond the available data returns empty response

### ISSUE THREAD

**Issue by ktatarnikovhiro** [glaciation-heu/IceStream#189]
LAKE: please investigate and fix

**Comment by fpetke** [comment]
I tried with the query shown in Appendix D of this [document](https://mefgovit.sharepoint.com/:w:/r/sites/glaciation/Documenti%20condivisi/General/6.%20Work%20Package%206%20-%20Edge-Core-Cloud%20platform/Biweekly--meeting/WP6-BiWeekly-2024-10-15.docx?d=wa630c8c5a63c47678f971cebdb010c79&csf=1&web=1&e=DTSx2Y).

Metadata Service returns an empty response indeed, because it receives the SPARQL query as a single line query, and if there are comments on any of the intermediate lines, it considers everything after the comment a comment.
