### ISSUE TITLE
Triggering of Jena garbage collection is crashing

### ISSUE THREAD

**Issue by a-zharinov** [glaciation-heu/IceStream#197]
# Summary
Metadata Service craches when triggers Apache Jena Fuseki to compact the database. It is a blokcer for #188.

# Logs
Logs of Metadata Servcie side car container indicate a connection issue:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v0/graph/compact (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ce32f6c60>: Failed to establish a new 
```
You can find more logs [here](http://grafana.integration/d/o6-BGgnnk/loki-kubernetes-logs?orgId=1&var-query=&var-namespace=All&var-stream=All&var-container=drop-graphs-sidecar&from=1733755384422&to=1733755492046).
The log shows a wrong hostname and URL of Apache Jena Fuseki.

# How to validate the fix
In Itegration cluster, Apache Jena Fuseki should show multiple successfull tasks of compaction. At the moment it [shows](http://jena-fuseki.integration/#/manage/tasks) the only one triggered by me manually.
![Image](https://github.com/user-attachments/assets/23aaf164-1473-4147-8abd-81f3cdeb95b1)

**Comment by fpetke** [comment]
The issue is that the *metadata-service* container crashes. It happens when there are many **drop** queries to send to Jena. At the beginning I thought that it would be because I'm sending these queries to the *metadata-service* container from the *drop-graphs-sidecar* one-by-one and a **drop** query takes relatively a lot of time to be processed. So I tried sending a single request to the *metadata-service* container and then split it there, so the queries can be sent one-by-one to Jena (Jena cannot process multiple **drop** queries at once, even when separated by semicolons).

**Note that** the sidecar sends a request for compaction to the main container, as I wanted to keep the main container as the only interaction-point with Jena.

The problem then is that when the sidecar would send a request to the main container to trigger the compaction, it cannot reach the main container, because it's restarting. Otherwise the triggering is already validated and works.

Also, somehow on Longhorn it still shows that the volume has 99.9 GB used out of 100 GB. Would it be possible to remove and then recreate the volume?

**Comment by a-zharinov** [comment]
@fpetke, I re-created the volume and created a [dashboard](http://grafana.integration/d/be6i6k21gv20wa/apache-jena-fuseki?orgId=1&from=1733834977158&to=1733856577158) to track its size.

**Comment by fpetke** [comment]
Currently there are 2 separate schedules:
- The graphs are checked every 5 minutes, and if there are named graphs older than 6 hours, they are dropped. This means that 5 graphs are deleted every 5 minutes, and we chose this DROP frequency because dropping a graph takes 2-3 seconds, so we don't want to make metadata service unavailable for a long time. This is also the reason why Metadata Service was restarting frequently, so increasing the probe interval and timeout helped.
- The compaction is triggered every hour.

All of these time intervals can be modified in the [values.yaml](https://github.com/glaciation-heu/glaciation-metadata-service/blob/main/server/charts/server/values.yaml) file of Metadata Service.

Grafana shows what we expect, because after every compaction, the space usage drops:
![s1Dwbp1q043yfuAW](https://github.com/user-attachments/assets/fbdf06dd-ccc5-4737-ae54-270edaf8e02a)

However, Longhorn shows a higher amount of Actual Size, which is probably not going do decrease then. And this one is also stable now.
![cOhN6mfpCu8Ygg7Y](https://github.com/user-attachments/assets/adb49fd6-4496-4442-a14d-a49921c9dec6)

The number of named graphs is also stable, and then depends on the cutoff we want to use to determine which named graphs we want to store.
